/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDeviceFab: typeof import('./components/devices/add-device-fab.vue')['default']
    AddTopicsBtn: typeof import('./components/devices/topics/add-topics-btn.vue')['default']
    AlertTop: typeof import('./components/alert-top.vue')['default']
    DeleteDeviceBtn: typeof import('./components/devices/delete-device-btn.vue')['default']
    DeleteTopicsBtn: typeof import('./components/devices/topics/delete-topics-btn.vue')['default']
    NavigationBar: typeof import('./components/navigation-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
